project:
  type: website
  output-dir: docs

website:
  title: "ACCDMi"
  navbar:
    background:  "#440154"
    logo: "images/logo/accdmi-logo-icon-only.png"
    left:
      - href: index.qmd
        text: Home
      - href: members.qmd
        text: Members
      - href: trainees.qmd
        text: Trainees
      - href: research.qmd
        text: Research
      - href: publications.qmd
        text: Publications
      - href: activities.qmd
        text: Activities

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
